-- Enable Row Level Security
alter table if exists trades enable row level security;
alter table if exists volume_profiles enable row level security;

-- Create trades table
create table if not exists trades (
  id bigint generated by default as identity primary key,
  symbol text not null,
  type text not null check (type in ('buy', 'sell')),
  entry_price numeric not null,
  stop_loss numeric,
  take_profit numeric,
  stars text,
  conditions jsonb,
  status text not null default 'open' check (status in ('open', 'closed', 'tp_hit', 'sl_hit')),
  exit_price numeric,
  profit_loss numeric,
  exit_reason text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create volume_profiles table
create table if not exists volume_profiles (
  id bigint generated by default as identity primary key,
  symbol text not null,
  session_date date not null,
  vp_data jsonb not null default '{}',
  total_volume numeric not null default 0,
  net_delta numeric not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(symbol, session_date)
);

-- Create indexes
create index if not exists idx_trades_status on trades(status);
create index if not exists idx_trades_created_at on trades(created_at desc);
create index if not exists idx_volume_profiles_symbol_date on volume_profiles(symbol, session_date);

-- Disable RLS for now (no auth)
alter table trades disable row level security;
alter table volume_profiles disable row level security;

-- Insert test data (optional)
insert into trades (symbol, type, entry_price, stop_loss, take_profit, stars, status) 
values 
  ('PAXGUSDT', 'buy', 2150.50, 2145.00, 2165.00, '★★★★★', 'open'),
  ('BTCUSDT', 'sell', 43200.00, 43500.00, 42800.00, '★★★', 'open')
on conflict do nothing;
